title: Yadav Family
author: Yadav Family
email: admin@yadav.cloud
description: >
  Yadav Family

baseurl: ""
url: https://yadav.cloud

timezone: Asia/Kolkata
encoding: "utf-8"
exclude: ['README.markdown']

permalink: posts/:title/

collections:
  recipes:
    output: true
    permalink: /recipes/:path

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
